### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by FrancBanc** [lightsoutgames/godot-tts#1]
This works on Windows, but when I export to android, there is no text to speech. I assume it is supposed to connect to the google text to speech api?

I don't know if this will help, but in the ADB logcat is gives this error:

**ERROR**:  does not have a library for the current platform.
At: modules/gdnative/nativescript/nativescript.cpp:1483:init_library() - Condition "lib_path.length() == 0" is true.
TTS not available!

**Comment by ndarilek** [comment]
The Android export process isn't quite as seamless. You first need to [set up custom builds](https://docs.godotengine.org/en/latest/getting_started/workflow/export/android_custom_build.html), then add games/lightsout/godot/tts/TTS to your list of Android modules in the project. Then copy or symlink the android/ directory under the custom build template location and it should work. I need to upgrade the plugin so it works with the new 3.2.2 plugin system, though that will unfortunately tie it to a specific Godot version.

Let me know if that works for you or if you have other issues.

**Comment by FrancBanc** [comment]
Hi, thank you for the response. 

I added "games/lightsout/godot/tts/TTS" to the Android modules setting, and copied the folder res://addons/android to res://android. 
It worked! Thank you for the additional instructions! 

The final directory for the TTS Java file is res://android/android/src/games/lightsout/godot/tts/


It works on 3.2.1 and 3.2.2 so I don't think you don't really have to update it for the new plugin system if that's too hard to do. I think the only thing that changes between each new godot version is the user will have to delete the custom build folder and make a new one, then add your android folder to it again.
If you could update the instructions for anyone in the future that would be great. I imagine there are many people that would be interested in text-to-speech for their Godot games or applications!

**Comment by ndarilek** [comment]
Cool, thanks for confirming that this works! I'll see if I can work 
those instructions into the README in the next few days.

**Comment by FrancBanc** [comment]
Great! 
I actually just noticed, that on Windows, if you interrupt speech with another speech, it freezes. However If you do let a speech fully finish, and then start a new speech, it works fine. 

If you'd like I'll open a new issue, and let me know what info I can give you about it.

**Comment by ndarilek** [comment]
Yeah, a new issue with a reproduction project would be useful. Also, be 
sure to let me know which platform you're using (I.e. desktop or UWP) 
since those can use different synths.
