### ISSUE TITLE
Is there anyway to adjust volume?

### ISSUE THREAD

**Issue by KekLuck** [lightsoutgames/godot-tts#6]
Hey thanks for all your work!

But I cant seem to figure out how the volume works. Even if I put the master bus to 0 it plays on full volume. Since there is no function in the class, is there a way to work around this? Im a beginner programmer but it seems to have the functions somewhere in those librarys but I cant seem to find a way to access it.

Thanks!

**Comment by ndarilek** [comment]
No, volume isn't currently supported. Also, it doesn't use the existing 
sound bus, so changing that will have no effect. Sorry.

**Comment by dylanjaide** [comment]
> No, volume isn't currently supported.

Are there any plans to add support for this @ndarilek ?

Thanks also for all the work on this making this addon - I've found it really easy to use! :) the missing volume control is currently the only thing that might cause problems with using this for our project.

**Comment by ndarilek** [comment]
I probably won't get to this since I don't use Godot anymore, but it 
should be easy enough to add and I'd accept a PR for it. Look to the 
rate setter/getter as an example. I bet you can just copy-paste the rate 
code, change "rate" to "volume" and you'd be mostly there. The 
underlying library supports it, I just haven't exported that 
functionality to the Godot plugin.

**Comment by dylanjaide** [comment]
Hi @ndarilek , I've now opened https://github.com/lightsoutgames/godot-tts/pull/7. At the moment it's tested and working for browsers and with the Godot editor on Win10, but I haven't been able to test on Mac/Linux/Android

**Comment by ndarilek** [comment]
Awesome, I'll look it over and merge/release on Monday. Thanks!

**Comment by teddybear082** [comment]
Hi I am using this as a mod for the game cruelty squad to give character's voices and wondering if it might be possible to implement the pull request that was submitted for volume? I can make the gd side changes myself but don't have the knowledge to implement the rest and compile myself. Thanks so much for your work, this is awesome!
