### ISSUE TITLE
[Upstream] godot-rust is not compatible with Godot 3.5 

### ISSUE THREAD

**Issue by Cheeseness** [lightsoutgames/godot-tts#8]
godot-tts currently breaks in Godot 3.5 during GDNative initilisation, complaining about Godot 4.0 compatibility due to an incorrect version check in godot-rust.

Making note to track upstream https://github.com/godot-rust/godot-rust/pull/910 which addresses compatibility issues with Godot 3.5, which was released earlier today.

**Comment by Bromeon** [comment]
It looks like this project [uses `gdnative` v0.9](https://github.com/lightsoutgames/godot-tts/blob/master/Cargo.toml#L12), which is more than a year old and no longer maintained. Current version is v0.10.

I plan to integrate the Godot 3.5 compatibility changes to godot-rust's `master` when I find some time, and hopefully also release a new crates.io version not too long after.

> complaining about Godot 4.0 compatibility due to an incorrect version check in godot-rust.

This bug in particular should already have been fixed in https://github.com/godot-rust/godot-rust/pull/909.

**Comment by Bromeon** [comment]
Update: Godot 3.5.1 is now officially supported with `gdnative 0.11.0`.

**Comment by Cheeseness** [comment]
> Update: Godot 3.5.1 is now officially supported with `gdnative 0.11.0`.

Thanks for your efforts and the heads up!

**Comment by Cheeseness** [comment]
@ndarilek List time we spoke, I think you said you were happy to look into bumping dependencies once 3.5.x was behaving with upstream godot-rust. Is this still on your radar?

**Comment by ndarilek** [comment]
So sorry, going to try getting to it this week. Need to sort out macOS issues and push out an upstream release first.

I'm going to try to keep everything compatible, but would you be able to handle necessary GDScript changes if there are any? I can't easily test things on Godot anymore.

Also, I'm assuming you don't have a local Rust build environment set up? If I sent you a test build, would you be able to test it, and what platform would you need?

**Comment by Cheeseness** [comment]
Sounds good.

Reading up, I can't see any documented GDScript API changes.

I don't have a Rust build env set up at the moment (and my build server is currently out of action), but I'd be happy to deploy test builds of one of my games to my testers/do some testing on Linux.

**Comment by Cheeseness** [comment]
If you're comfortable @ndarilek, I think we can mark this resolved with the 0.8.0 release

**Comment by ndarilek** [comment]
Done, thanks for the reminder.
