### ISSUE TITLE
0.8.0 Requires newer GLIBC than current stable Debian release

### ISSUE THREAD

**Issue by Cheeseness** [lightsoutgames/godot-tts#9]
The latest version of Godot TTS links against GLIBC 2.34 symbols, while some distros are still on older versions. GLIBC's forward compatibility strategy does not allow things compiled against newer GLIBC to be backward compatible with older versions.

Debian stable (11.5) is currently using GLIBC 2.31.

There are a couple of strategies for addressing this sort of thing, but the simplest approach is usually to use a Debian Stable build environment for release builds.

**Comment by ndarilek** [comment]
Hmm, not immediately sure what to do about this. If I stick with GitHub CI, the list of runners I can use is here:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
Ubuntu 20.04 is available but only has glibc 2.31, which is apparently too old for the Rust library which minimally supports 2.32.
Not immediately sure what the solution is here. I can migrate CI, but I'd need something that supported Linux, Windows, and macOS. I'm running my own server for Lights Out Games, but the easiest way to use that would be migrating off of GitHub onto my own Gitea instance,. And that would make collaboration more difficult.
Are you able to build your own Linux builds in Docker or similar in the meantime? I'll see if I can figure out the best migration strategy for this project.

**Comment by Cheeseness** [comment]
Hmm, I can see how that makes things a little awkward. Are you using pre-compiled Rust libs? I don't use Rust for anything, so I haven't had to navigate this specifically, but I see on their docs' Platform Support page that "Tier 1" support for x86_64 Linux is still targeting GLIBC 2.17. Only MIPS and ARM architectures are listed as targeting GLIBC 2.32.
https://doc.rust-lang.org/nightly/rustc/platform-support.html

There are a couple of cludgy ways of modifying the symbol table or forcing the compiler to link against a specific GLIBC versions' symbols, but I'm not sure if they're a good fit for this kind of situation.

As I said, I can set up a build environment for my own projects longer term, but that's not something I'm expecting to have time for within the next few months. I am content to sit on Godot 3.4 with the version of Godot TTS I'm already shipping with builds for now, so no stress/pressure from this end.

**Comment by ndarilek** [comment]
If my root cause analysis is correct, the issue isn't with Rust but with 
the Rust GDNative bindings. I think they, or possibly their libc 
dependency, bottoms out at 2.32.

I might be wrong, but if you look one commit back in the history where I 
drop the CI machines to use Ubuntu 20.04, you'll see a lot of 
glibc-related failures. Cracking open an ubuntu:20.04 Docker image pulls 
in libc-dev 2.31.

I'll see what I can figure out longer-term but it likely involves 
migrating the project.

If my analysis is wrong then hopefully someone can let me know. I'd 
rather not move this project unless I have to. :)

**Comment by Cheeseness** [comment]
Oh, I see. From a brief look at the Godot-Rust project, I can't see anything that is explicitly using or linking against a particular GLIBC symbols. I don't know enough about Cargo/Crates to know whether Godot Rust is being built or using upstream-built binaries as part of the current CI setup, but if it's the latter, I would imagine that's where that requirement is coming from.

Definitely don't migrate away from comfortable processes/workflows for me or my projects, though.

**Comment by Cheeseness** [comment]
I forgot to follow up on this - Debian 12 (Bookworm) was released last year, and resolves this issue.
